// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT
using Content.Shared.DeadSpace.SignBoard;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.SignBoard.UI;

[GenerateTypedNameReferences]
public sealed partial class SignBoardWindow : DefaultWindow
{
    public event Action<string>? OnTextSubmitted;

    public SignBoardWindow()
    {
        RobustXamlLoader.Load(this);

        SignBoardInput.OnTextChanged += OnTextChanged;
        SignBoardInput.OnTextEntered += OnTextEntered;
        DrawButton.OnPressed += OnDrawPressed;
    }

    private void OnTextChanged(LineEdit.LineEditEventArgs args)
    {
        DrawButton.Disabled = string.IsNullOrWhiteSpace(args.Text);
    }

    private void OnTextEntered(LineEdit.LineEditEventArgs args)
    {
        if (!string.IsNullOrWhiteSpace(args.Text))
        {
            OnTextSubmitted?.Invoke(args.Text);
            Close();
        }
    }

    private void OnDrawPressed(BaseButton.ButtonEventArgs args)
    {
        var text = SignBoardInput.Text;
        if (!string.IsNullOrWhiteSpace(text))
        {
            OnTextSubmitted?.Invoke(text);
            Close();
        }
    }

    public void UpdateState(string text)
    {
        SignBoardInput.Text = text;
    }
}
